version: '3.7'

services:
 
  worker:
    image: eassbhhtgu/asndenier:latest
    environment:
      DOTNET_ENVIRONMENT: Production

      #ASNNumbers:amazon:0: 7224
      #ASNNumbers:amazon:1: 8987
      #ASNNumbers:amazon:2: 14618
      #ASNNumbers:amazon:3: 16509
      #ASNNumbers:amazon:4: 62785

      ASNNumbers:apple:0: 714
      ASNNumbers:apple:1: 6185

      ASNNumbers:epicgames:0: 4356

      ASNNumbers:facebook:0: 32934
      ASNNumbers:facebook:1: 54115
      ASNNumbers:facebook:2: 63293

      ASNNumbers:netflix:0: 2906
      ASNNumbers:netflix:1: 40027
      ASNNumbers:netflix:2: 55095

      ASNNumbers:tiktok:0: 138699

      ASNNumbers:twitter:0: 13414
      ASNNumbers:twitter:1: 35995
      ASNNumbers:twitter:2: 63179
      ASNNumbers:twitter:3: 63194

      ASNNumbers:whatsapp:0: 11917

      Router:PathToPrivateKey: /run/secrets/id_rsa

    secrets:
    - source: id_rsa

secrets:
  id_rsa:
    file: ${USERPROFILE}\.ssh\id_rsa
